<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>ZenithAudio</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Icono.ico</ApplicationIcon>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WindowsPackageType>None</WindowsPackageType>
    <Version>1.0.7</Version>
    <AssemblyVersion>1.0.7.0</AssemblyVersion>
    <FileVersion>1.0.7.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscUtils.Iso9660" Version="0.16.13" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260416003" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Update="App.xaml.cs">
      <DependentUpon>App.xaml</DependentUpon>
    </Compile>
    <Compile Update="MainWindow.xaml.cs">
      <DependentUpon>MainWindow.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Include="runtimes\win-x64\native\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="zenithai.defaults.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Icono.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Logo.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
